# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems:             ["jekyll-paginate"]

# Permalinks
permalink:        pretty

# Setup
title:            Club-Méta
heading:          Club-<br />Méta
tagline:          'Bienvenue au club !'
description:      'Regarde tout ce qu''on peut faire avec de la caféine ! Fait par <a href="https://twitter.com/jjvie" target="_blank">@jjvie</a>.'
url:              http://club-meta.fr
baseurl:          /

authors:
  jjv:
    name: 'Jill-Jênn Vie'
    email: anonymous@club-meta.fr
    web: http://jill-jenn.net/
    twitter: jjvie
    github: jilljenn
  kocobe:
    name: 'Kocobe'
    email:
    web:
    twitter:
    github: kocobe


paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/jilljenn/club-meta
